version: 2.1

jobs:
  build:
    parallelism: 2
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.2-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: rails-app-with-knapsack_pro
          RAILS_ENV: test
          RACK_ENV: test
          # You can ignore this ENV variable: it's for internal testing by Knapsack Pro devs.
          KNAPSACK_PRO_REPO_PATH: ~/knapsack_pro-ruby
          # You can ignore this ENV variable: it's for internal testing by Knapsack Pro devs.
          KNAPSACK_PRO_ENDPOINT: https://api-staging.knapsackpro.com

          # Tokens are set in CircleCI settings so you can't read them from this file.
          # KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: rspec-token
          # KNAPSACK_PRO_TEST_SUITE_TOKEN_CUCUMBER: cucumber-token
          # KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST: minitest-token
          # KNAPSACK_PRO_TEST_SUITE_TOKEN_SPINACH: spinach-token

      - image: cimg/postgres:14.7
        environment:
          POSTGRES_DB: rails-app-with-knapsack_pro_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: rails-app-with-knapsack_pro
    steps:
      - checkout
      - run:
          working_directory: ~/knapsack_pro-ruby
          command: git clone --depth 1 --branch $CIRCLE_BRANCH --single-branch git@github.com:KnapsackPro/knapsack_pro-ruby.git ./ || git clone --depth 1 git@github.com:KnapsackPro/knapsack_pro-ruby.git ./
      - run:
          working_directory: ~/knapsack_pro-ruby
          command: git branch
      - run:
          name: Show last commit
          working_directory: ~/knapsack_pro-ruby
          command: git log -n 1 --pretty=oneline
      - run: mkdir -p tmp/test-reports/rspec/regular_mode/
      - run: mkdir -p tmp/test-reports/rspec/queue_mode/
      - run: mkdir -p tmp/test-reports/cucumber/regular_mode/
      - run: mkdir -p tmp/test-reports/cucumber/queue_mode/
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - restore_cache:
          keys:
          - v2-dependencies-bundler-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-bundler-
      - run:
          name: Install ruby dependencies
          command: |
            bundle config set --local path './vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-bundler-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for postgres to be available
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bin/rails db:setup
      - run:
          name: Database setup for parallel_tests gem
          command: TEST_ENV_NUMBER=2 bin/rails db:setup

      # Queue Mode: Minitest
      - run:
          command: |
            export KNAPSACK_PRO_RSPEC_DISABLED=true
            export KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE=/tmp/tests_to_run.txt
            # Retrieve the tests to run (all or just the failed ones), and let Knapsack Pro split them optimally.
            circleci tests glob "test/**/*_test.rb" | circleci tests run --index 0 --total 1 --command ">$KNAPSACK_PRO_TEST_FILE_LIST_SOURCE_FILE xargs -n1 echo" --verbose
            bundle exec rake "knapsack_pro:queue:minitest[--verbose --ci-report --no-ci-clean]"

      - store_test_results:
          path: test/reports

  upload-coverage:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.2-browsers
    environment:
      CC_TEST_REPORTER_ID: dd360701bd9bd47abdea789fe94c9a9b118bc9f7fbce6d3cdc1dd3709866e460
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          command: |
            ./cc-test-reporter sum-coverage --output - codeclimate.*.json | ./cc-test-reporter upload-coverage --debug --input -

workflows:
  commit:
    jobs:
      - build
      - upload-coverage:
          requires:
             - build
